ktor:
    application:
        modules:
            - utn.methodology.ApplicationKt.module
    deployment:
        port: 8080

db:
    mongo:
        user: '$MONGO_USERNAME:local'
        password: '$MONGO_PASSWORD:secret'